name = "Vdiff"
uuid = "a4e6b4e8-4b97-4be9-afa4-72a10a6a8f69"
authors = ["Jean Michel <jean.michel@imj-prg.fr> and contributors"]
version = "0.0.1"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d" 
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
TextUserInterfaces = "2a09ff82-1be9-11e9-2ab7-19964783a84b"
Ncurses = "247b9857-0442-4f1c-b9a0-de109b4a5af1"

[compat]
Dates = "1"
Ncurses = "0.1.0"
OrderedCollections = "1"
Printf = "1"
TextUserInterfaces = "0.0.1"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
